line_length: 130

file_length:
  warning: 500
  error: 1200

disabled_rules:
  - variable_name
  - todo
  - valid_docs

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - ARCLTests
